//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18408
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrderManagement.CPViewDetailService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://common.connector.dataservice.gov.org/", ConfigurationName="CPViewDetailService.ICPViewDetail")]
    public interface ICPViewDetail {
        
        // CODEGEN: 命名空间  的元素名称 paramXml 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        CPViewDetailService.commonProductViewDetailResponse commonProductViewDetail(CPViewDetailService.commonProductViewDetail request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class commonProductViewDetail {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="commonProductViewDetail", Namespace="http://common.connector.dataservice.gov.org/", Order=0)]
        public CPViewDetailService.commonProductViewDetailBody Body;
        
        public commonProductViewDetail() {
        }
        
        public commonProductViewDetail(CPViewDetailService.commonProductViewDetailBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class commonProductViewDetailBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string paramXml;
        
        public commonProductViewDetailBody() {
        }
        
        public commonProductViewDetailBody(string paramXml) {
            this.paramXml = paramXml;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class commonProductViewDetailResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="commonProductViewDetailResponse", Namespace="http://common.connector.dataservice.gov.org/", Order=0)]
        public CPViewDetailService.commonProductViewDetailResponseBody Body;
        
        public commonProductViewDetailResponse() {
        }
        
        public commonProductViewDetailResponse(CPViewDetailService.commonProductViewDetailResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class commonProductViewDetailResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public commonProductViewDetailResponseBody() {
        }
        
        public commonProductViewDetailResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICPViewDetailChannel : CPViewDetailService.ICPViewDetail, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CPViewDetailClient : System.ServiceModel.ClientBase<CPViewDetailService.ICPViewDetail>, CPViewDetailService.ICPViewDetail {
        
        public CPViewDetailClient() {
        }
        
        public CPViewDetailClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CPViewDetailClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CPViewDetailClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CPViewDetailClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CPViewDetailService.commonProductViewDetailResponse CPViewDetailService.ICPViewDetail.commonProductViewDetail(CPViewDetailService.commonProductViewDetail request) {
            return base.Channel.commonProductViewDetail(request);
        }
        
        public string commonProductViewDetail(string paramXml) {
            CPViewDetailService.commonProductViewDetail inValue = new CPViewDetailService.commonProductViewDetail();
            inValue.Body = new CPViewDetailService.commonProductViewDetailBody();
            inValue.Body.paramXml = paramXml;
            CPViewDetailService.commonProductViewDetailResponse retVal = ((CPViewDetailService.ICPViewDetail)(this)).commonProductViewDetail(inValue);
            return retVal.Body.@return;
        }
    }
}
