//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18408
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrderManagement.CPRequireSubmitService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://common.order.connector.dataservice.gov.org/", ConfigurationName="CPRequireSubmitService.ICPRequireSubmit")]
    public interface ICPRequireSubmit {
        
        // CODEGEN: 命名空间  的元素名称 paramXml 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        CPRequireSubmitService.commonProductRequireSubmitResponse commonProductRequireSubmit(CPRequireSubmitService.commonProductRequireSubmit request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class commonProductRequireSubmit {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="commonProductRequireSubmit", Namespace="http://common.order.connector.dataservice.gov.org/", Order=0)]
        public CPRequireSubmitService.commonProductRequireSubmitBody Body;
        
        public commonProductRequireSubmit() {
        }
        
        public commonProductRequireSubmit(CPRequireSubmitService.commonProductRequireSubmitBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class commonProductRequireSubmitBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string paramXml;
        
        public commonProductRequireSubmitBody() {
        }
        
        public commonProductRequireSubmitBody(string paramXml) {
            this.paramXml = paramXml;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class commonProductRequireSubmitResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="commonProductRequireSubmitResponse", Namespace="http://common.order.connector.dataservice.gov.org/", Order=0)]
        public CPRequireSubmitService.commonProductRequireSubmitResponseBody Body;
        
        public commonProductRequireSubmitResponse() {
        }
        
        public commonProductRequireSubmitResponse(CPRequireSubmitService.commonProductRequireSubmitResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class commonProductRequireSubmitResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public commonProductRequireSubmitResponseBody() {
        }
        
        public commonProductRequireSubmitResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICPRequireSubmitChannel : CPRequireSubmitService.ICPRequireSubmit, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CPRequireSubmitClient : System.ServiceModel.ClientBase<CPRequireSubmitService.ICPRequireSubmit>, CPRequireSubmitService.ICPRequireSubmit {
        
        public CPRequireSubmitClient() {
        }
        
        public CPRequireSubmitClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CPRequireSubmitClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CPRequireSubmitClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CPRequireSubmitClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CPRequireSubmitService.commonProductRequireSubmitResponse CPRequireSubmitService.ICPRequireSubmit.commonProductRequireSubmit(CPRequireSubmitService.commonProductRequireSubmit request) {
            return base.Channel.commonProductRequireSubmit(request);
        }
        
        public string commonProductRequireSubmit(string paramXml) {
            CPRequireSubmitService.commonProductRequireSubmit inValue = new CPRequireSubmitService.commonProductRequireSubmit();
            inValue.Body = new CPRequireSubmitService.commonProductRequireSubmitBody();
            inValue.Body.paramXml = paramXml;
            CPRequireSubmitService.commonProductRequireSubmitResponse retVal = ((CPRequireSubmitService.ICPRequireSubmit)(this)).commonProductRequireSubmit(inValue);
            return retVal.Body.@return;
        }
    }
}
