//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18408
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrderManagement.CPStateFeedbackService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://common.order.connector.dataservice.gov.org/", ConfigurationName="CPStateFeedbackService.ICPStateFeedback")]
    public interface ICPStateFeedback {
        
        // CODEGEN: 命名空间  的元素名称 paramXml 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        CPStateFeedbackService.stateResponse state(CPStateFeedbackService.state request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class state {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="state", Namespace="http://common.order.connector.dataservice.gov.org/", Order=0)]
        public CPStateFeedbackService.stateBody Body;
        
        public state() {
        }
        
        public state(CPStateFeedbackService.stateBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class stateBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string paramXml;
        
        public stateBody() {
        }
        
        public stateBody(string paramXml) {
            this.paramXml = paramXml;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class stateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="stateResponse", Namespace="http://common.order.connector.dataservice.gov.org/", Order=0)]
        public CPStateFeedbackService.stateResponseBody Body;
        
        public stateResponse() {
        }
        
        public stateResponse(CPStateFeedbackService.stateResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class stateResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public stateResponseBody() {
        }
        
        public stateResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICPStateFeedbackChannel : CPStateFeedbackService.ICPStateFeedback, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CPStateFeedbackClient : System.ServiceModel.ClientBase<CPStateFeedbackService.ICPStateFeedback>, CPStateFeedbackService.ICPStateFeedback {
        
        public CPStateFeedbackClient() {
        }
        
        public CPStateFeedbackClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CPStateFeedbackClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CPStateFeedbackClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CPStateFeedbackClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CPStateFeedbackService.stateResponse CPStateFeedbackService.ICPStateFeedback.state(CPStateFeedbackService.state request) {
            return base.Channel.state(request);
        }
        
        public string state(string paramXml) {
            CPStateFeedbackService.state inValue = new CPStateFeedbackService.state();
            inValue.Body = new CPStateFeedbackService.stateBody();
            inValue.Body.paramXml = paramXml;
            CPStateFeedbackService.stateResponse retVal = ((CPStateFeedbackService.ICPStateFeedback)(this)).state(inValue);
            return retVal.Body.@return;
        }
    }
}
