
  CREATE TABLE "ST"."GXORDER" 
   (	"ORDERID" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"PRODUCTNAME" VARCHAR2(60 BYTE), 
	"PRODUCTTYPE" VARCHAR2(60 BYTE), 
	"COVERSCOPE" VARCHAR2(60 BYTE), 
	"STARTDATE" VARCHAR2(20 BYTE), 
	"ENDDATE" VARCHAR2(20 BYTE), 
	"CREATEDAT" DATE, 
	"CREATEDBY" VARCHAR2(50 BYTE), 
	"LASTUPDATEDAT" DATE, 
	"LASTUPDATEDBY" VARCHAR2(50 BYTE), 
	"DELETEDAT" DATE, 
	"DELETEDBY" VARCHAR2(50 BYTE), 
	"TIMESTAMP" TIMESTAMP (6), 
	"ISDELETED" NUMBER(1,0), 
	"RID" VARCHAR2(30 BYTE), 
	"STATUS" VARCHAR2(100 BYTE), 
	"COMM_ORDER_ID" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
 

  CREATE UNIQUE INDEX "ST"."INDEX1" ON "ST"."GXORDER" ("ORDERID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
 

  CREATE OR REPLACE TRIGGER "ST"."GXORDER_TRIGGER" 
BEFORE INSERT ON GXORDER 

for each row

BEGIN

 select GXORDER_SEQ.nextval into :new.ORDERID from dual;
 
 END;
/
ALTER TRIGGER "ST"."GXORDER_TRIGGER" ENABLE;
 
