
  CREATE TABLE "ST"."TASK_ORDER_STATUS" 
   (	"ID" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"TASK_ORDER_ID" VARCHAR2(20 BYTE), 
	"STATUS_SECTION" VARCHAR2(100 BYTE), 
	"STATUS_DESC" VARCHAR2(100 BYTE), 
	"START_DATE" DATE, 
	"END_DATE" DATE, 
	"IS_LAST_STATUS" VARCHAR2(20 BYTE), 
	"CREATEDAT" DATE, 
	"CREATEDBY" VARCHAR2(50 BYTE), 
	"LASTUPDATEDAT" DATE, 
	"LASTUPDATEDBY" VARCHAR2(50 BYTE), 
	"DELETEDAT" DATE, 
	"DELETEDBY" VARCHAR2(50 BYTE), 
	"TIMESTAMP" TIMESTAMP (6), 
	"ISDELETED" NUMBER(1,0), 
	"TIME_COST" VARCHAR2(20 BYTE), 
	 CONSTRAINT "order_status_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
 

  CREATE OR REPLACE TRIGGER "ST"."ORDER_STATUS_TR" 
BEFORE INSERT ON TASK_ORDER_STATUS 
for each row
BEGIN
 select ORDER_STATUS_SEQ.nextval into :new.ID from dual;
END;
/
ALTER TRIGGER "ST"."ORDER_STATUS_TR" ENABLE;
 
