//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18408
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrderManagement.ICPFTPsubmit {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://common.order.connector.dataservice.gov.org/", ConfigurationName="ICPFTPsubmit.ICPFTPSubmit")]
    public interface ICPFTPSubmit {
        
        // CODEGEN: 命名空间  的元素名称 paramXml 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        ICPFTPsubmit.commonProductSubmitResponse commonProductSubmit(ICPFTPsubmit.commonProductSubmit request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class commonProductSubmit {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="commonProductSubmit", Namespace="http://common.order.connector.dataservice.gov.org/", Order=0)]
        public ICPFTPsubmit.commonProductSubmitBody Body;
        
        public commonProductSubmit() {
        }
        
        public commonProductSubmit(ICPFTPsubmit.commonProductSubmitBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class commonProductSubmitBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string paramXml;
        
        public commonProductSubmitBody() {
        }
        
        public commonProductSubmitBody(string paramXml) {
            this.paramXml = paramXml;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class commonProductSubmitResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="commonProductSubmitResponse", Namespace="http://common.order.connector.dataservice.gov.org/", Order=0)]
        public ICPFTPsubmit.commonProductSubmitResponseBody Body;
        
        public commonProductSubmitResponse() {
        }
        
        public commonProductSubmitResponse(ICPFTPsubmit.commonProductSubmitResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class commonProductSubmitResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public commonProductSubmitResponseBody() {
        }
        
        public commonProductSubmitResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICPFTPSubmitChannel : ICPFTPsubmit.ICPFTPSubmit, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CPFTPSubmitClient : System.ServiceModel.ClientBase<ICPFTPsubmit.ICPFTPSubmit>, ICPFTPsubmit.ICPFTPSubmit {
        
        public CPFTPSubmitClient() {
        }
        
        public CPFTPSubmitClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CPFTPSubmitClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CPFTPSubmitClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CPFTPSubmitClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ICPFTPsubmit.commonProductSubmitResponse ICPFTPsubmit.ICPFTPSubmit.commonProductSubmit(ICPFTPsubmit.commonProductSubmit request) {
            return base.Channel.commonProductSubmit(request);
        }
        
        public string commonProductSubmit(string paramXml) {
            ICPFTPsubmit.commonProductSubmit inValue = new ICPFTPsubmit.commonProductSubmit();
            inValue.Body = new ICPFTPsubmit.commonProductSubmitBody();
            inValue.Body.paramXml = paramXml;
            ICPFTPsubmit.commonProductSubmitResponse retVal = ((ICPFTPsubmit.ICPFTPSubmit)(this)).commonProductSubmit(inValue);
            return retVal.Body.@return;
        }
    }
}
