//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18408
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrderManagement.CPOrderStateFeedbackService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://common.order.connector.dataservice.gov.org/", ConfigurationName="CPOrderStateFeedbackService.ICPOrderStateFeedback")]
    public interface ICPOrderStateFeedback {
        
        // CODEGEN: 命名空间  的元素名称 paramXml 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        CPOrderStateFeedbackService.commonProductStateFeedbackResponse commonProductStateFeedback(CPOrderStateFeedbackService.commonProductStateFeedback request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class commonProductStateFeedback {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="commonProductStateFeedback", Namespace="http://common.order.connector.dataservice.gov.org/", Order=0)]
        public CPOrderStateFeedbackService.commonProductStateFeedbackBody Body;
        
        public commonProductStateFeedback() {
        }
        
        public commonProductStateFeedback(CPOrderStateFeedbackService.commonProductStateFeedbackBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class commonProductStateFeedbackBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string paramXml;
        
        public commonProductStateFeedbackBody() {
        }
        
        public commonProductStateFeedbackBody(string paramXml) {
            this.paramXml = paramXml;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class commonProductStateFeedbackResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="commonProductStateFeedbackResponse", Namespace="http://common.order.connector.dataservice.gov.org/", Order=0)]
        public CPOrderStateFeedbackService.commonProductStateFeedbackResponseBody Body;
        
        public commonProductStateFeedbackResponse() {
        }
        
        public commonProductStateFeedbackResponse(CPOrderStateFeedbackService.commonProductStateFeedbackResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class commonProductStateFeedbackResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public commonProductStateFeedbackResponseBody() {
        }
        
        public commonProductStateFeedbackResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICPOrderStateFeedbackChannel : CPOrderStateFeedbackService.ICPOrderStateFeedback, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CPOrderStateFeedbackClient : System.ServiceModel.ClientBase<CPOrderStateFeedbackService.ICPOrderStateFeedback>, CPOrderStateFeedbackService.ICPOrderStateFeedback {
        
        public CPOrderStateFeedbackClient() {
        }
        
        public CPOrderStateFeedbackClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CPOrderStateFeedbackClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CPOrderStateFeedbackClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CPOrderStateFeedbackClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CPOrderStateFeedbackService.commonProductStateFeedbackResponse CPOrderStateFeedbackService.ICPOrderStateFeedback.commonProductStateFeedback(CPOrderStateFeedbackService.commonProductStateFeedback request) {
            return base.Channel.commonProductStateFeedback(request);
        }
        
        public string commonProductStateFeedback(string paramXml) {
            CPOrderStateFeedbackService.commonProductStateFeedback inValue = new CPOrderStateFeedbackService.commonProductStateFeedback();
            inValue.Body = new CPOrderStateFeedbackService.commonProductStateFeedbackBody();
            inValue.Body.paramXml = paramXml;
            CPOrderStateFeedbackService.commonProductStateFeedbackResponse retVal = ((CPOrderStateFeedbackService.ICPOrderStateFeedback)(this)).commonProductStateFeedback(inValue);
            return retVal.Body.@return;
        }
    }
}
