//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18408
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrderManagement.FFGS_WEQ_Service {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="FFGS_WEQ_Service.IFFGS_WEQ")]
    public interface IFFGS_WEQ {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFFGS_WEQ/Model_FFGS_WEQ", ReplyAction="http://tempuri.org/IFFGS_WEQ/Model_FFGS_WEQResponse")]
        string Model_FFGS_WEQ(string btnInFileTRKSX, string btnInFileSDZS, string btnInFileFS, string btnInFileCCD, string btnInFileZBFGD, string btnOutFile);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IFFGS_WEQChannel : OrderManagement.FFGS_WEQ_Service.IFFGS_WEQ, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FFGS_WEQClient : System.ServiceModel.ClientBase<OrderManagement.FFGS_WEQ_Service.IFFGS_WEQ>, OrderManagement.FFGS_WEQ_Service.IFFGS_WEQ {
        
        public FFGS_WEQClient() {
        }
        
        public FFGS_WEQClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FFGS_WEQClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FFGS_WEQClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FFGS_WEQClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string Model_FFGS_WEQ(string btnInFileTRKSX, string btnInFileSDZS, string btnInFileFS, string btnInFileCCD, string btnInFileZBFGD, string btnOutFile) {
            return base.Channel.Model_FFGS_WEQ(btnInFileTRKSX, btnInFileSDZS, btnInFileFS, btnInFileCCD, btnInFileZBFGD, btnOutFile);
        }
    }
}
