//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18408
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrderManagement.CPFtpFeedbackService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://common.order.connector.dataservice.gov.org/", ConfigurationName="CPFtpFeedbackService.ICPFtpFeedback")]
    public interface ICPFtpFeedback {
        
        // CODEGEN: 命名空间  的元素名称 paramXml 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
       CPFtpFeedbackService.ftpFeedbackResponse ftpFeedback(CPFtpFeedbackService.ftpFeedback request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ftpFeedback {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ftpFeedback", Namespace="http://common.order.connector.dataservice.gov.org/", Order=0)]
        public CPFtpFeedbackService.ftpFeedbackBody Body;
        
        public ftpFeedback() {
        }
        
        public ftpFeedback(CPFtpFeedbackService.ftpFeedbackBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class ftpFeedbackBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string paramXml;
        
        public ftpFeedbackBody() {
        }
        
        public ftpFeedbackBody(string paramXml) {
            this.paramXml = paramXml;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ftpFeedbackResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ftpFeedbackResponse", Namespace="http://common.order.connector.dataservice.gov.org/", Order=0)]
        public CPFtpFeedbackService.ftpFeedbackResponseBody Body;
        
        public ftpFeedbackResponse() {
        }
        
        public ftpFeedbackResponse(CPFtpFeedbackService.ftpFeedbackResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class ftpFeedbackResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public ftpFeedbackResponseBody() {
        }
        
        public ftpFeedbackResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICPFtpFeedbackChannel : CPFtpFeedbackService.ICPFtpFeedback, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CPFtpFeedbackClient : System.ServiceModel.ClientBase<CPFtpFeedbackService.ICPFtpFeedback>, CPFtpFeedbackService.ICPFtpFeedback {
        
        public CPFtpFeedbackClient() {
        }
        
        public CPFtpFeedbackClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CPFtpFeedbackClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CPFtpFeedbackClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CPFtpFeedbackClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CPFtpFeedbackService.ftpFeedbackResponse CPFtpFeedbackService.ICPFtpFeedback.ftpFeedback(CPFtpFeedbackService.ftpFeedback request) {
            return base.Channel.ftpFeedback(request);
        }
        
        public string ftpFeedback(string paramXml) {
           CPFtpFeedbackService.ftpFeedback inValue = new CPFtpFeedbackService.ftpFeedback();
            inValue.Body = new CPFtpFeedbackService.ftpFeedbackBody();
            inValue.Body.paramXml = paramXml;
            CPFtpFeedbackService.ftpFeedbackResponse retVal = ((CPFtpFeedbackService.ICPFtpFeedback)(this)).ftpFeedback(inValue);
            return retVal.Body.@return;
        }
    }
}
