//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18408
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrderManagement.CPQueryService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://common.connector.dataservice.gov.org/", ConfigurationName="CPQueryService.ICPQuery")]
    public interface ICPQuery {
        
        // CODEGEN: 命名空间  的元素名称 paramXml 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        CPQueryService.commonProductQueryResponse commonProductQuery(CPQueryService.commonProductQuery request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class commonProductQuery {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="commonProductQuery", Namespace="http://common.connector.dataservice.gov.org/", Order=0)]
        public CPQueryService.commonProductQueryBody Body;
        
        public commonProductQuery() {
        }
        
        public commonProductQuery(CPQueryService.commonProductQueryBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class commonProductQueryBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string paramXml;
        
        public commonProductQueryBody() {
        }
        
        public commonProductQueryBody(string paramXml) {
            this.paramXml = paramXml;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class commonProductQueryResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="commonProductQueryResponse", Namespace="http://common.connector.dataservice.gov.org/", Order=0)]
        public CPQueryService.commonProductQueryResponseBody Body;
        
        public commonProductQueryResponse() {
        }
        
        public commonProductQueryResponse(CPQueryService.commonProductQueryResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class commonProductQueryResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public commonProductQueryResponseBody() {
        }
        
        public commonProductQueryResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICPQueryChannel : CPQueryService.ICPQuery, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CPQueryClient : System.ServiceModel.ClientBase<CPQueryService.ICPQuery>, CPQueryService.ICPQuery {
        
        public CPQueryClient() {
        }
        
        public CPQueryClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CPQueryClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CPQueryClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CPQueryClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CPQueryService.commonProductQueryResponse CPQueryService.ICPQuery.commonProductQuery(CPQueryService.commonProductQuery request) {
            return base.Channel.commonProductQuery(request);
        }
        
        public string commonProductQuery(string paramXml) {
            CPQueryService.commonProductQuery inValue = new CPQueryService.commonProductQuery();
            inValue.Body = new CPQueryService.commonProductQueryBody();
            inValue.Body.paramXml = paramXml;
            CPQueryService.commonProductQueryResponse retVal = ((CPQueryService.ICPQuery)(this)).commonProductQuery(inValue);
            return retVal.Body.@return;
        }
    }
}
