//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18408
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrderManagement.CPFeasibilitySubmitService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://common.order.connector.dataservice.gov.org/", ConfigurationName="CPFeasibilitySubmitService.ICPFeasibilitySubmit")]
    public interface ICPFeasibilitySubmit {
        
        // CODEGEN: 命名空间  的元素名称 paramXml 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        CPFeasibilitySubmitService.feasibilitySubmitResponse feasibilitySubmit(CPFeasibilitySubmitService.feasibilitySubmit request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class feasibilitySubmit {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="feasibilitySubmit", Namespace="http://common.order.connector.dataservice.gov.org/", Order=0)]
        public CPFeasibilitySubmitService.feasibilitySubmitBody Body;
        
        public feasibilitySubmit() {
        }
        
        public feasibilitySubmit(CPFeasibilitySubmitService.feasibilitySubmitBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class feasibilitySubmitBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string paramXml;
        
        public feasibilitySubmitBody() {
        }
        
        public feasibilitySubmitBody(string paramXml) {
            this.paramXml = paramXml;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class feasibilitySubmitResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="feasibilitySubmitResponse", Namespace="http://common.order.connector.dataservice.gov.org/", Order=0)]
        public CPFeasibilitySubmitService.feasibilitySubmitResponseBody Body;
        
        public feasibilitySubmitResponse() {
        }
        
        public feasibilitySubmitResponse(CPFeasibilitySubmitService.feasibilitySubmitResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class feasibilitySubmitResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public feasibilitySubmitResponseBody() {
        }
        
        public feasibilitySubmitResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICPFeasibilitySubmitChannel : CPFeasibilitySubmitService.ICPFeasibilitySubmit, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CPFeasibilitySubmitClient : System.ServiceModel.ClientBase<CPFeasibilitySubmitService.ICPFeasibilitySubmit>, CPFeasibilitySubmitService.ICPFeasibilitySubmit {
        
        public CPFeasibilitySubmitClient() {
        }
        
        public CPFeasibilitySubmitClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CPFeasibilitySubmitClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CPFeasibilitySubmitClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CPFeasibilitySubmitClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CPFeasibilitySubmitService.feasibilitySubmitResponse CPFeasibilitySubmitService.ICPFeasibilitySubmit.feasibilitySubmit(CPFeasibilitySubmitService.feasibilitySubmit request) {
            return base.Channel.feasibilitySubmit(request);
        }
        
        public string feasibilitySubmit(string paramXml) {
            CPFeasibilitySubmitService.feasibilitySubmit inValue = new CPFeasibilitySubmitService.feasibilitySubmit();
            inValue.Body = new CPFeasibilitySubmitService.feasibilitySubmitBody();
            inValue.Body.paramXml = paramXml;
            CPFeasibilitySubmitService.feasibilitySubmitResponse retVal = ((CPFeasibilitySubmitService.ICPFeasibilitySubmit)(this)).feasibilitySubmit(inValue);
            return retVal.Body.@return;
        }
    }
}
