//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18408
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrderManagement.TPOrderSubmitService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://thematic.order.connector.dataservice.gov.org/", ConfigurationName="TPOrderSubmitService.ITPOrderSubmit")]
    public interface ITPOrderSubmit {
        
        // CODEGEN: 命名空间  的元素名称 paramXml 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        TPOrderSubmitService.thematicProductOrderSubmitResponse thematicProductOrderSubmit(TPOrderSubmitService.thematicProductOrderSubmit request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class thematicProductOrderSubmit {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="thematicProductOrderSubmit", Namespace="http://thematic.order.connector.dataservice.gov.org/", Order=0)]
        public TPOrderSubmitService.thematicProductOrderSubmitBody Body;
        
        public thematicProductOrderSubmit() {
        }
        
        public thematicProductOrderSubmit(TPOrderSubmitService.thematicProductOrderSubmitBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class thematicProductOrderSubmitBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string paramXml;
        
        public thematicProductOrderSubmitBody() {
        }
        
        public thematicProductOrderSubmitBody(string paramXml) {
            this.paramXml = paramXml;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class thematicProductOrderSubmitResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="thematicProductOrderSubmitResponse", Namespace="http://thematic.order.connector.dataservice.gov.org/", Order=0)]
        public TPOrderSubmitService.thematicProductOrderSubmitResponseBody Body;
        
        public thematicProductOrderSubmitResponse() {
        }
        
        public thematicProductOrderSubmitResponse(TPOrderSubmitService.thematicProductOrderSubmitResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class thematicProductOrderSubmitResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public thematicProductOrderSubmitResponseBody() {
        }
        
        public thematicProductOrderSubmitResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITPOrderSubmitChannel : TPOrderSubmitService.ITPOrderSubmit, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TPOrderSubmitClient : System.ServiceModel.ClientBase<TPOrderSubmitService.ITPOrderSubmit>, TPOrderSubmitService.ITPOrderSubmit {
        
        public TPOrderSubmitClient() {
        }
        
        public TPOrderSubmitClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TPOrderSubmitClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TPOrderSubmitClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TPOrderSubmitClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TPOrderSubmitService.thematicProductOrderSubmitResponse TPOrderSubmitService.ITPOrderSubmit.thematicProductOrderSubmit(TPOrderSubmitService.thematicProductOrderSubmit request) {
            return base.Channel.thematicProductOrderSubmit(request);
        }
        
        public string thematicProductOrderSubmit(string paramXml) {
            TPOrderSubmitService.thematicProductOrderSubmit inValue = new TPOrderSubmitService.thematicProductOrderSubmit();
            inValue.Body = new TPOrderSubmitService.thematicProductOrderSubmitBody();
            inValue.Body.paramXml = paramXml;
            TPOrderSubmitService.thematicProductOrderSubmitResponse retVal = ((TPOrderSubmitService.ITPOrderSubmit)(this)).thematicProductOrderSubmit(inValue);
            return retVal.Body.@return;
        }
    }
}
