//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18408
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrderManagement.CPHandleSubmitService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://common.order.connector.dataservice.gov.org/", ConfigurationName="CPHandleSubmitService.ICPHandleSubmit")]
    public interface ICPHandleSubmit {
        
        // CODEGEN: 命名空间  的元素名称 paramXml 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        CPHandleSubmitService.commonProductHandleSubmitResponse commonProductHandleSubmit(CPHandleSubmitService.commonProductHandleSubmit request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class commonProductHandleSubmit {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="commonProductHandleSubmit", Namespace="http://common.order.connector.dataservice.gov.org/", Order=0)]
        public CPHandleSubmitService.commonProductHandleSubmitBody Body;
        
        public commonProductHandleSubmit() {
        }
        
        public commonProductHandleSubmit(CPHandleSubmitService.commonProductHandleSubmitBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class commonProductHandleSubmitBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string paramXml;
        
        public commonProductHandleSubmitBody() {
        }
        
        public commonProductHandleSubmitBody(string paramXml) {
            this.paramXml = paramXml;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class commonProductHandleSubmitResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="commonProductHandleSubmitResponse", Namespace="http://common.order.connector.dataservice.gov.org/", Order=0)]
        public CPHandleSubmitService.commonProductHandleSubmitResponseBody Body;
        
        public commonProductHandleSubmitResponse() {
        }
        
        public commonProductHandleSubmitResponse(CPHandleSubmitService.commonProductHandleSubmitResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class commonProductHandleSubmitResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public commonProductHandleSubmitResponseBody() {
        }
        
        public commonProductHandleSubmitResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICPHandleSubmitChannel : CPHandleSubmitService.ICPHandleSubmit, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CPHandleSubmitClient : System.ServiceModel.ClientBase<CPHandleSubmitService.ICPHandleSubmit>, CPHandleSubmitService.ICPHandleSubmit {
        
        public CPHandleSubmitClient() {
        }
        
        public CPHandleSubmitClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CPHandleSubmitClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CPHandleSubmitClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CPHandleSubmitClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CPHandleSubmitService.commonProductHandleSubmitResponse CPHandleSubmitService.ICPHandleSubmit.commonProductHandleSubmit(CPHandleSubmitService.commonProductHandleSubmit request) {
            return base.Channel.commonProductHandleSubmit(request);
        }
        
        public string commonProductHandleSubmit(string paramXml) {
            CPHandleSubmitService.commonProductHandleSubmit inValue = new CPHandleSubmitService.commonProductHandleSubmit();
            inValue.Body = new CPHandleSubmitService.commonProductHandleSubmitBody();
            inValue.Body.paramXml = paramXml;
            CPHandleSubmitService.commonProductHandleSubmitResponse retVal = ((CPHandleSubmitService.ICPHandleSubmit)(this)).commonProductHandleSubmit(inValue);
            return retVal.Body.@return;
        }
    }
}
